// Auto-generated by quantize_weights.py — do not edit manually.
// Quantization parameters for cnn_inference.sv on Nexys A7-100T.
package cnn_params_pkg;

// Per-layer right-shift: apply to INT32 accumulator to produce INT8 activation.
// Conservative (worst-case) — guarantees no overflow.
    localparam int CONV1_SHIFT = 10;
    localparam int CONV2_SHIFT = 15;
    localparam int CONV3_SHIFT = 16;
    localparam int FC1_SHIFT   = 16;
    localparam int FC2_SHIFT   = 14;

// BRAM depths for $readmemh (one byte per address).
    localparam int CONV1_W_DEPTH =    160;   // 32 x 1 x 5
    localparam int CONV1_B_DEPTH =     32;
    localparam int CONV2_W_DEPTH =  10240;   // 64 x 32 x 5
    localparam int CONV2_B_DEPTH =     64;
    localparam int CONV3_W_DEPTH =  40960;   // 128 x 64 x 5
    localparam int CONV3_B_DEPTH =    128;
    localparam int FC1_W_DEPTH   =  65536;   // 128 x 512
    localparam int FC1_B_DEPTH   =    128;
    localparam int FC2_W_DEPTH   =    640;   // 5 x 128
    localparam int FC2_B_DEPTH   =      5;

endpackage
